version: '3'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Doemaarwat1
      MYSQL_DATABASE: casbin-golang
      MYSQL_USER: admin
      MYSQL_PASSWORD: LekkerLekker123
    networks:
      - db_network
  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Doemaarwat1 
    networks:
      - db_network
networks:
  db_network:
volumes:
  db_data: